apiVersion: v1
kind: Pod
metadata:
  name: priv-pod
  namespace: default
spec:
  containers:
  - name: priv-pod
    image: alpine
    command: ["tail"]
    args: ["-f", "/dev/null"] 
    securityContext:
       privileged: true