apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      #- image: dockersamples/examplevotingapp_vote:before
      - image: 172.20.0.11:32000/vote:0.0.14
        name: vote
        ports:
        - containerPort: 80
          name: vote
        securityContext:
            privileged: true
