# redis
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: redis
  name: redis
spec: 
  clusterIP: None
  ports:
  - name: redis-service
    port: 6379
    targetPort: 6379
  selector: 
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: redis

# db
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: db
  name: db
spec: 
  clusterIP: None
  ports: 
  - name: db
    port: 5432
    targetPort: 5432
  selector: 
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:9.4
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# result
---
apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 80
    name: result-service
  selector:
    app: result
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: dockersamples/examplevotingapp_result:before
        ports:
        - containerPort: 80
          name: result

# vote
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    apps: vote
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 80
      name: vote-service
  selector:
    app: vote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        # image: dockersamples/examplevotingapp_vote:before
        image: 535849429554.dkr.ecr.us-east-1.amazonaws.com/voteapp/vote:latest
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
          name: vote

# worker
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: worker
  name: worker
spec: 
  clusterIP: None
  selector: 
    app: worker
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: worker
  name: worker
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template: 
    metadata: 
      labels: 
        app: worker
    spec: 
      containers: 
      - image: dockersamples/examplevotingapp_worker
        name: worker
# maintenance
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: maintenance
  name: maintenance
spec: 
  clusterIP: None
  selector: 
    app: maintenance
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: maintenance
  name: maintenance
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: maintenance
  template: 
    metadata: 
      labels: 
        app: maintenance
    spec: 
      containers: 
      - image: ubuntu
        command: ["tail"]
        volumeMounts:
        - mountPath: "/root/.aws"
          name: backup-credentials
          readOnly: true
        args: ["-f","/dev/null"]
        env:
        - name: AWS_ACCESS_KEY_ID
          value: AKIA35U2TGKSG6XGJRNV
        - name: AWS_SECRET_ACCESS_KEY
          value: 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
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        name: maintenance
      volumes:
      - name: backup-credentials
        secret:
          secretName: backup-credentials
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backup-credentials
  namespace: default
data:
    credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPUFLSUEzNVUyVEdLU0c2WEdKUk5WCmF3c19zZWNyZXRfYWNjZXNzX2tleT11R3NxNmp0VnMxeVYwVEVwUTMrVktOZU4ybUFsdzNZQ1FWK3hDT2FOCmF3c19kZWZhdWx0X3JlZ2lvbj11cy13ZXN0LTIK
# kali
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: kalilinux
  name: kalilinux
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: kalilinux
  template: 
    metadata: 
      labels: 
        app: kalilinux
    spec: 
      containers: 
      - image: kalilinux/kali-rolling
        command: ["tail"]
        args: ["-f","/dev/null"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:  
  - image: alpine
    name: test-container
    command: ["tail"]
    args: ["-f", "/dev/null"] 
    volumeMounts:
    - mountPath: /host
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /
      # this field is optional
      type: Directory
