apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-service-account
  namespace: <namespace>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: <namespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccountName: redis-service-account
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379