apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-service-account
  namespace: <namespace>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: <namespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      serviceAccountName: web-service-account
      containers:
      - name: web-service
        image: <your-flask-app-image>
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: <namespace>
spec:
  selector:
    app: web-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80