apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-service-account
  namespace: <namespace>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: <namespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: worker-service-account
      containers:
        - name: worker
          image: <your-worker-app-image>
          ports:
            - containerPort: 8080