apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
    - image: nginx:1.23.1-alpine
      imagePullPolicy: IfNotPresent
      name: alpine
      ports:
        - containerPort: 5000
  restartPolicy: Always
