---
queryId: TF_CUSTOM_AWS_EC2_TAG_QUERY
queryText: |-
  {
      source {
          CloudTrailRawEvents
      }
      filter {
          EVENT_SOURCE = 'ec2.amazonaws.com'
          and EVENT_NAME = 'DescribeTags'
          and ERROR_CODE is null
      }
      return distinct {
          INSERT_ID,
          INSERT_TIME,
          EVENT_TIME,
          EVENT
      }
  }